import type { Metadata } from "next"; // Enables type checking for Metadata
import { Inter } from "next/font/google"; // Impors the Inter font from google fonts 
import "./globals.css"; // Imports the css formatting file
import Link from 'next/link'; // Imports the Link component for client side navigation

const inter = Inter({ subsets: ["latin"] }); // Initializes the Inter font to use througout the application

// Defines metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Defines the Root Layout component that will wrap child components with the standardized page layout detailed below
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Returns the layout HTML structure for use in all the pages
  return (
    <html lang="en">
      <body> {/* Starts the body of the page */}
        <header> {/* HTML tag for a header to be displayed at the top of every page */}
        <div className="navbar"> {/* Container for the navigator bar */}
        <h1 className="home"><Link href="/">Home</Link></h1> {/* Home text contained by the navbar */}
        <a className="globalButton"> {/* button css formatting */}
          <Link href="/about">About Pymetrics</Link>
          </a> {/* link to the About page */}
        <a className="globalButton"> {/* button css formatting */}
          <Link href="/practice_home">Practice</Link>
          </a> {/* link to the Practice page (home) */}
        <a className="globalButton"> {/* button css formatting */}
          <Link href="/services">Services</Link>
          </a> {/* link to the Services page */}
        <div className="buttonsRightContainer"> {/* Container for the login and subscribe which I wanted to be aligned to the right */}
          <a className="globalFarRightButton"> {/* Right button css formatting that puts the button on the far right of the screen */}
            <Link href="/login">Login</Link>
            </a> {/* Right-aligned button with a link for Login */}
          <a className="globalFarRightButton"> {/* Right button css formatting that puts the button on the far right of the screen */}
            <Link href="/subscribe">Subscribe</Link>
            </a> {/* Right-aligned button with a link for Subscribe */}
        </div> {/* Ends the right aligned container for the right buttons */}
      </div> {/* Ends the navbar */}
        </header> {/* Encloses the HTML for the header which will be a navigation bar */}
        
      {children} {/*Renders the child components in the layout (Such as the navigation bar that I used for the whole site.)  */}
      </body> {/* End of the body */}
    </html> /* End of the HTML section */
  );
}
